#define NPY_SORT_DISPATCH 0
#define NPY_SORT_FALLBACK 1
#define NPY_SORT_FNS 2

#define FNS_ALL 0
#define FNS_GUARDED 1
#define FNS_COPY 2
#define FNS_OVERLAP 3

#define JOIN_HELPER(X,Y) X ## Y
#define JOIN(X,Y) JOIN_HELPER(X,Y)
#define NPY_SORT_FUNC JOIN(sort_,NPY_SORT_POWER)

// CHANGE BELOW

#define NPY_SORT_TYPE NPY_SORT_FNS
#define FNS_TYPE FNS_GUARDED
#define NPY_SORT_BASE 16
#define NPY_SORT_POWER NPY_SORT_BASE
#define NPY_SORT_DEBUG
#define NPY_SORT_CHECK